'use strict';
OR.dialogue=(()=>{
  // Each encounter represents a different person; these are shared voices, not biographies.
  const raw={
    villager:{
      strongwood:[
        ['life','I came out for a quiet walk. Everyone else seems to have had the same idea.'],
        ['life','My roof leaks over the good chair. Naturally, that is where the cat insists on sleeping.'],
        ['life','Someone left a pie on my doorstep. I am choosing gratitude over investigation.'],
        ['life','We trade recipes when the road is safe and rumors when it is not.'],
        ['life','My youngest has decided the moon is an egg. I have no better explanation ready.'],
        ['life','There is a particular kind of peace in hearing your own kettle from the garden.'],
        ['life','The baker says my account is overdue. I say his bread is too small. We remain friends.'],
        ['life','I keep a spare place at supper. Sometimes kindness needs somewhere to sit.'],
        ['tip','Your cottage is at zero, zero. Even the longest walk has an address to come back to.'],
        ['tip','Rest at home and your health returns, even while you are away from the game.'],
        ['tip','A potion restores all your health. Save it for a wound worth the cork.'],
        ['tip','Tap WPN or ARM to improve your gear. You need ingots, not a special place to stand.'],
        ['tip','Metal strengthens armor. Steel strengthens weapons. The smiths are very particular about that.'],
        ['tip','Your map remembers discovered places. It cannot tell you what is still hidden.'],
        ['tip','Keep Walking is a perfectly respectable answer to trouble.'],
        ['rambling','The fourth fence post is listening. I only tell the first three anything important.'],
        ['rambling','I found a button in my soup. Now I wonder what coat the soup was wearing.'],
        ['rambling','A cloud followed me home yesterday. I would have invited it in, but the roof objected.'],
        ['rambling','Do you think shadows get tired of standing? Mine looks exhausted.'],
        ['rambling','I have counted the village twice. There is always one more chimney when I sneeze.'],
        ['gruff','If this is about the missing bucket, speak to someone with wetter shoes.'],
        ['gruff','No, I do not know a shortcut. If I did, I would already be gone.'],
        ['gruff','I have spent all morning being pleasant. You have arrived just after closing.'],
        ['gruff','Take your heroic stomping somewhere else. Some of us are thinking.'],
        ['gruff','You want wisdom? Stop blocking the path. There, free wisdom.']
      ],
      outer:[
        ['life','I used to complain about the noise back home. I would pay to hear it now.'],
        ['life','I brought a spoon because it felt like a promise that there would be another meal.'],
        ['life','My coat still smells of hearth smoke. I try not to let the ash cover it.'],
        ['life','I mend socks while I wait. Fear is easier when your hands have something ordinary to do.'],
        ['life','There was a house here once. I remember because its door was a terrible shade of blue.'],
        ['life','I keep rehearsing what I will say when I get home. Mostly, it is asking for tea.'],
        ['life','We made a game of guessing the weather. Out here, everyone keeps guessing wrong.'],
        ['life','I am carrying a letter that should have been delivered years ago. Better late, I suppose.'],
        ['tip','Cross past twenty-five in either direction and you are outside Strongwood. Mind both coordinates.'],
        ['tip','A key opens a locked chest, then it is gone. Make the opening count.'],
        ['tip','A gem can buy your way out of a fight. Pride is a poor substitute for supplies.'],
        ['tip','Falling sends you home with one breath left. It does not empty your pack.'],
        ['tip','Rest only restores health at home. Waiting out here will not mend a thing.'],
        ['tip','If you are badly hurt and have no potion, watch the path as you walk. Help can turn up.'],
        ['tip','The journal keeps recent events. Read it when the days start running together.'],
        ['rambling','That ruined doorway has moved since this morning. Or the morning has moved.'],
        ['rambling','The fog borrowed my name. If it introduces itself, do not be polite.'],
        ['rambling','I counted nine footsteps after I stopped. One of us is cheating.'],
        ['rambling','Somewhere behind the red sky there is a perfectly ordinary sky having a very bad day.'],
        ['rambling','The stones whisper in their sleep. Nothing useful, mostly complaints about moss.'],
        ['gruff','I am not a landmark. Find your own way.'],
        ['gruff','Do I look like I packed enough hope for two people?'],
        ['gruff','Keep your questions short. The quiet is already angry with us.'],
        ['gruff','If you want comforting lies, go back to the village. I have run out.'],
        ['gruff','I saw nothing. I heard nothing. I would very much like to continue doing both.']
      ],
      attacked:[
        ['angry','Put that away! I am a person, not a practice stump.'],
        ['angry','Is that how they taught you to ask directions?'],
        ['angry','Missed me. Now try missing me from farther away.'],
        ['angry','I left home to avoid an argument, not to audition for a murder.'],
        ['angry','You call yourself a defender? Start with defending your manners.'],
        ['angry','Touch my coat and I will send you the tailoring bill.'],
        ['angry','There are actual monsters nearby. Do you need them labeled?'],
        ['angry','I have survived worse than you before breakfast. My family visits.'],
        ['angry','Enough! Take your weapon and your terrible judgment elsewhere.'],
        ['angry','One more swing and I start describing you unkindly to everyone I meet.']
      ]
    },
    farmer:{
      strongwood:[
        ['life','Rain on washing day, sunshine on planting day. The sky has a cruel little sense of humor.'],
        ['life','My hens have appointed themselves owners of the yard. I merely pay the expenses.'],
        ['life','You can measure a good year by how often the neighbors borrow baskets.'],
        ['life','The first green shoot gets me every spring. All that work, and then a tiny answer.'],
        ['life','My brother grows prize turnips. Nobody has explained why anyone should win a turnip.'],
        ['life','I planted flowers by the pig pen. Beauty should not be reserved for the well-behaved.'],
        ['life','A full cellar is a lovely thing. A full table is better.'],
        ['life','There is always one goat that considers every fence a personal insult.'],
        ['tip','Digging costs health with every foot. Check your vitality before you start.'],
        ['tip','Buried treasure takes several feet of digging. The first scoop is not the harvest.'],
        ['tip','A failed dig still costs effort. The ground owes nobody a reward.'],
        ['tip','Rest at your cottage before another expedition. Home does more for wounds than stubbornness.'],
        ['tip','Your pack counts the ingots you have. An upgrade takes the amount shown, no promises accepted.'],
        ['tip','Armor cuts incoming damage. A little reinforcement can matter over several fights.'],
        ['tip','Uncleared ground can turn dangerous on a return visit. A threat you defeat stays gone.'],
        ['rambling','My scarecrow faces east at dawn and west at dusk. I refuse to ask how.'],
        ['rambling','The cabbages have been discussing me. They go quiet when I water them.'],
        ['rambling','A worm brought me a pebble. Either we are friends now or I owe rent.'],
        ['rambling','I dreamt I was a potato. Best sleep I have had in weeks.'],
        ['rambling','The rooster crowed at an empty chair. I think he is running for something.'],
        ['gruff','Unless you can weed while talking, this conversation is costing me daylight.'],
        ['gruff','Those are seedlings under your boots. Try being heroic six inches to the left.'],
        ['gruff','I have heard enough predictions. Bring rain or bring a shovel.'],
        ['gruff','No, you cannot borrow the good bucket. That is how it becomes the missing bucket.'],
        ['gruff','I know the world is in danger. The beans still need picking.']
      ],
      outer:[
        ['life','I rub the soil between my fingers out of habit. It does not feel like soil anymore.'],
        ['life','These seeds came from my old garden. I keep them dry even when I cannot keep myself dry.'],
        ['life','I miss the sound of rain on the barn. This ash lands without a word.'],
        ['life','There used to be an orchard down that slope. I still count the rows.'],
        ['life','I brought a sack for the harvest. It is carrying my blankets now.'],
        ['life','We used to argue over whose apples were sweetest. Such a fine, useless argument.'],
        ['life','A living weed would cheer me up. Never thought I would say that.'],
        ['life','I have kept one good onion. It reminds me that the world once knew how to grow things.'],
        ['tip','Dig only while you can afford the health. Treasure is not much use from a sickbed.'],
        ['tip','If digging leaves you with one health, you are carried home. The unfinished hole stays here.'],
        ['tip','A potion can restore you during battle. You need not wait for the fighting to end.'],
        ['tip','Leave home before you are healed and the rest stops. Recovery does not follow you down the road.'],
        ['tip','You can improve your gear out here through WPN and ARM. Keep an eye on your ingots.'],
        ['tip','Every weapon upgrade asks for more steel than the last. Plan for the next one, too.'],
        ['tip','Locked chests need keys. All the staring in the world will not turn a lock.'],
        ['rambling','The furrows filled themselves in last night. Something below dislikes straight lines.'],
        ['rambling','I planted a bean and heard a laugh. I have decided to leave it alone.'],
        ['rambling','There are roots here with no trees attached. They must be looking for work.'],
        ['rambling','The scarecrow is gone. Its hat came back, and I do not care to know why.'],
        ['rambling','I heard a harvest bell under the ground. Wrong season. Wrong direction.'],
        ['gruff','Do not ask what I am growing. At present, resentment.'],
        ['gruff','No food to spare. No cheerful stories, either.'],
        ['gruff','You want to help? Stop casting your shadow over the last patch of light.'],
        ['gruff','I have buried enough hopes here. I am not taking yours on as well.'],
        ['gruff','Leave the sack alone. It is mine, and that is the whole explanation.']
      ],
      attacked:[
        ['angry','I dodge angry goats for a living. You will have to do better than that.'],
        ['angry','Try that on a thistle patch. It might actually be useful.'],
        ['angry','You nearly cut my seed bag! Have you any idea what a season costs?'],
        ['angry','I grow food. You apparently grow problems.'],
        ['angry','Put the weapon away before you frighten something with more sense than you.'],
        ['angry','If you need exercise, there is a field full of stones.'],
        ['angry','That swing had all the grace of a pig on ice.'],
        ['angry','My grandmother chased wolves with a rake. Do not test the family tradition.'],
        ['angry','No blood on the vegetables! Honestly, must everything be explained?'],
        ['angry','Go fight the darkness. I am busy fighting mildew.']
      ]
    },
    woodcutter:{
      strongwood:[
        ['life','A clean split is a small joy. I collect the small ones.'],
        ['life','This oak will warm three houses. I like knowing where my work goes.'],
        ['life','My shoulders predict rain better than the clouds. Less pleasantly, mind you.'],
        ['life','I carve little boats from the offcuts. The children are building quite a navy.'],
        ['life','The forest is never silent. You only need to stop making so much noise yourself.'],
        ['life','Fresh shavings smell like the first day of something.'],
        ['life','I promised to finish before supper. The tree has declined to cooperate.'],
        ['life','A neighbor fixed my boots, so I stacked their firewood. That is how a village works.'],
        ['tip','A heavy strike can miss. Read the accuracy as carefully as the power.'],
        ['tip','Tackle is almost certain to land, but it lacks the force of your weapon moves.'],
        ['tip','The axe hits hard. Execution is a gamble, though: only fifty-eight percent accuracy.'],
        ['tip','Steel ingots improve weapon power. Tap WPN when you have enough.'],
        ['tip','Each upgrade raises the price of the next. Even good iron demands patience.'],
        ['tip','A Lucky Coin adds five percentage points to your accuracy. It never raises it above certainty.'],
        ['tip','There is no shame in passing a fight. A sensible swing begins with a sensible choice.'],
        ['rambling','This stump looks like my uncle. More agreeable company, so far.'],
        ['rambling','I suspect the squirrels are auditing my timber. Their standards seem severe.'],
        ['rambling','A tree creaked my name once. I pretended it had the wrong person.'],
        ['rambling','If a branch falls while nobody is listening, it still makes a mess for me.'],
        ['rambling','I marked this log with chalk. Now every log looks smug about it.'],
        ['gruff','Stand clear. Conversation does not stop a falling branch.'],
        ['gruff','I am paid for wood, not commentary.'],
        ['gruff','If you have advice about my swing, keep it behind your teeth.'],
        ['gruff','That is a working axe. Kindly stop calling it charming.'],
        ['gruff','You have chosen the exact spot where I wanted to put this log.']
      ],
      outer:[
        ['life','This wood burns cold in the hand. I miss honest splinters.'],
        ['life','I brought my own wedge. Tools from home make unfamiliar work feel smaller.'],
        ['life','I used to listen for birds before felling a tree. I still wait, even here.'],
        ['life','One sound piece of timber. That is all I wanted from this walk.'],
        ['life','My partner says I talk to the wood too much. Out here, I wish it would stay wood.'],
        ['life','I keep finding old axe marks. It helps to know other hands came this way.'],
        ['life','There is a half-built cradle waiting at home. I intend to finish it.'],
        ['life','I have carried worse loads. None of them felt quite so far from the hearth.'],
        ['tip','A dragon keeps the wounds you give it, even if you flee. Not every job is finished in one visit.'],
        ['tip','Do not confuse a powerful move with a reliable one. Out here, the difference bites.'],
        ['tip','Realmfire needs a Magic Crystal. Keep one if you want that move ready.'],
        ['tip','Armor reduces a blow; it does not promise you will feel nothing.'],
        ['tip','The hammer’s Earthshaker lands half the time before any Lucky Coin bonus. Pick your moment.'],
        ['tip','You can flee an unfinished fight. The road will still be there.'],
        ['tip','Wounded and carrying no potion? Keep an eye out as you travel; the road can yield one.'],
        ['rambling','I split a log and found ash inside. The fire appears to be arriving out of order.'],
        ['rambling','These rings count backward. I do not want to meet the sapling.'],
        ['rambling','The branches point at me when the wind stops. Very rude trees.'],
        ['rambling','I heard chopping ahead. Every time I rested, it rested too.'],
        ['rambling','A knot in that trunk blinked. I am charging extra for this wood.'],
        ['gruff','Do not touch the stack. I counted it, and counting it hurt.'],
        ['gruff','Yes, the trees are dead. No, that does not make my job easy.'],
        ['gruff','Keep your voice down. I would prefer the forest remain uninterested.'],
        ['gruff','If you came for a story, pick a stump and invent your own.'],
        ['gruff','Move along. You are giving my bad day a face.']
      ],
      attacked:[
        ['angry','I know where an axe is going before the fool holding it does.'],
        ['angry','Trees stand still. I do not. Remember the distinction.'],
        ['angry','Keep swinging like that and you will break something you need.'],
        ['angry','You want a fight? Find something that is not earning its supper.'],
        ['angry','That was close to my thumb. I am rather attached to my thumb.'],
        ['angry','I have ducked heavier branches than you.'],
        ['angry','The chopping block is over there, if your eyes work.'],
        ['angry','Put it away. There is enough waste in this forest already.'],
        ['angry','Try asking nicely before you start swinging badly.'],
        ['angry','I could give you a lesson, but you could not afford my patience.']
      ]
    },
    hunter:{
      strongwood:[
        ['life','The tracks tell you where something went. The waiting tells you why.'],
        ['life','I spent an hour watching a fox bury nothing. We all need hobbies.'],
        ['life','My dog understands silence better than most people understand words.'],
        ['life','There is a hollow near the stream where the dawn arrives blue. Worth waking early for.'],
        ['life','I leave the young ones be. Tomorrow should have something living in it.'],
        ['life','A good pair of boots is a love letter to your future feet.'],
        ['life','I promised to bring back supper. Nobody specified an impressive supper.'],
        ['life','Once you know every tree on a path, coming home starts before the village.'],
        ['tip','Accuracy is your chance to land a hit. Power only matters when it connects.'],
        ['tip','Knife strikes are dependable. Stab starts at ninety-nine percent accuracy.'],
        ['tip','Enemies can miss too. Watch their result before choosing your next move.'],
        ['tip','A Lucky Coin stays in your pack and steadies every attack. You do not spend it.'],
        ['tip','Look at the map when you lose your bearings. Your own position is marked.'],
        ['tip','A quiet path may hide a new threat when you return. Ground you clear in battle stays safe.'],
        ['tip','The stronger blow is not always the better finish. Sometimes you only need a little damage.'],
        ['rambling','A hare stared at me until I apologized. I still do not know what I did.'],
        ['rambling','That owl knows my business. I can tell by its disappointing little face.'],
        ['rambling','I found tracks in a circle. Either a dance or a very confused escape.'],
        ['rambling','The wind brought me the smell of soup. There are no houses that way. Tragic.'],
        ['rambling','I once followed my own footprints for half a morning. Excellent tracker, questionable target.'],
        ['gruff','You are louder than your weapon. That takes effort.'],
        ['gruff','Step off the tracks before you ask me what made them.'],
        ['gruff','I was enjoying a conversation with nobody.'],
        ['gruff','If you must breathe that loudly, do it downwind.'],
        ['gruff','No trophies, no demonstrations, no stories about your last fight. I am working.']
      ],
      outer:[
        ['life','The old habits help: check the wind, check the ground, remember to breathe.'],
        ['life','I found a feather without ash on it. There must still be somewhere clean.'],
        ['life','My hands shake more here. I give them small tasks until they remember themselves.'],
        ['life','I used to hunt by birdsong. Now I notice how much I depended on it.'],
        ['life','There is a trail home in my head. I walk it whenever this place grows too quiet.'],
        ['life','I have no taste for trophies from this country. I only want to leave with what I brought.'],
        ['life','I keep one dry strip of cloth for my bow. Small precautions make good company.'],
        ['life','I saw something green beyond the ash. Perhaps a leaf. I needed it to be a leaf.'],
        ['tip','A dragon’s remaining health persists after retreat. You can return to finish what you started.'],
        ['tip','A gem buys a victory through bribery. It is another tool, not a confession of weakness.'],
        ['tip','Check your potion before starting a fight. The enemy will not wait for a shopping trip.'],
        ['tip','You cannot upgrade gear during a fight. Spend those ingots before you draw steel.'],
        ['tip','The gargoyle fights with talons and heavy wings. Stone hide softens your blows.'],
        ['tip','Realmfire has perfect accuracy, but each use consumes a crystal. Make it matter.'],
        ['tip','Winning enough battles raises your level and restores your health. Watch your victory count.'],
        ['rambling','These tracks begin in the middle of the road. I dislike beginnings without explanations.'],
        ['rambling','The thing behind me stopped breathing when I did. We are both being very patient.'],
        ['rambling','I saw a bird fly backward into the fog. It had the right idea.'],
        ['rambling','My shadow pointed north while I faced south. We are having a disagreement.'],
        ['rambling','There are hoofprints on that wall. I have decided the ground is plenty interesting.'],
        ['gruff','Do not announce our position just because you feel lonely.'],
        ['gruff','Whatever you heard, I heard it first. Let me listen.'],
        ['gruff','I can guide my own feet. You must take responsibility for yours.'],
        ['gruff','You are standing between me and my exit. Correct that.'],
        ['gruff','Save the questions for somewhere with fewer teeth.']
      ],
      attacked:[
        ['angry','I saw your shoulder move before your weapon did.'],
        ['angry','Predictable. Dangerous qualities should not come with predictable habits.'],
        ['angry','Try stalking your temper before you stalk me.'],
        ['angry','You have mistaken quiet for helpless. Common error.'],
        ['angry','I hunt things faster than you, and most of them think more carefully.'],
        ['angry','That swing told the whole forest where we are. Well done, fool.'],
        ['angry','Lower it. You are not the only one here who knows where a throat is.'],
        ['angry','You could have walked past. That was the clever option.'],
        ['angry','Miss again somewhere else.'],
        ['angry','Keep your weapon. Find yourself some judgment.']
      ]
    },
    elder:{
      strongwood:[
        ['life','I have forgotten whole winters and remembered one good afternoon. Memory has its priorities.'],
        ['life','The young think I sit here doing nothing. I am watching things I once walked past.'],
        ['life','My oldest friend and I disagree about everything except the importance of lunch.'],
        ['life','A house becomes a home slowly, then all at once when you must leave it.'],
        ['life','I used to save the good cups for visitors. Now I count myself as company.'],
        ['life','There are apologies I should have made sooner. Do not let yours grow roots.'],
        ['life','I planted that tree when my hands were steadier. It has managed rather well without them.'],
        ['life','Being needed is pleasant. Being allowed a nap is also pleasant.'],
        ['tip','Your journey is saved as you play in this browser. Keep the same browser to keep the same footsteps.'],
        ['tip','Strongwood reaches twenty-five tiles along either axis. Beyond that, the realm changes.'],
        ['tip','Five victories earn your first level. The later steps ask more of you.'],
        ['tip','Leveling strengthens your gear and fills your health. Growth should offer a little mercy.'],
        ['tip','One health means a journey home, not the end of your story.'],
        ['tip','You may leave home once your health rises above one. You need not wait until fully recovered.'],
        ['tip','The journal holds your recent history. It is shorter than a lifetime, but easier to carry.'],
        ['rambling','Time is a kettle with no handle. That sounded wiser before I said it.'],
        ['rambling','I owe a crow three favors. It has been too polite to collect, which worries me.'],
        ['rambling','The moon was smaller when I was young. Or perhaps I stood farther from the window.'],
        ['rambling','If you meet tomorrow, tell it I have questions about yesterday.'],
        ['rambling','I have misplaced a perfectly good thought. Check your pockets before you leave.'],
        ['gruff','Age is not an invitation to ask me about every pebble.'],
        ['gruff','No prophecy today. My knees predict rain; that is quite enough.'],
        ['gruff','If I wanted an audience, I would have brought a chair for you.'],
        ['gruff','I did not survive all these years to settle your argument with a signpost.'],
        ['gruff','Go on. Some of my best advice is given by pointing away.']
      ],
      outer:[
        ['life','I remember green here. Not clearly enough to paint it, but clearly enough to grieve.'],
        ['life','When the dark grows grand, think of something small you love. A cup. A voice. A stubborn flower.'],
        ['life','I have outlived several terrible certainties. I intend to outlive this one.'],
        ['life','There was a road song once. I remember the tune and none of the brave words.'],
        ['life','An old promise brought me here. I would advise making yours closer to home.'],
        ['life','I carry a smooth stone from the village stream. It asks nothing of me.'],
        ['life','The dead are not the only things worth remembering. Make room for the living.'],
        ['life','I have learned that courage sometimes looks like admitting you want to go home.'],
        ['tip','Rest only heals you at home. These ruins offer shelter to very different things.'],
        ['tip','Defeat leaves your discoveries and belongings intact. You have lost a fight, not your whole journey.'],
        ['tip','A wounded dragon remains wounded when you return. Even ancient things must live with consequences.'],
        ['tip','Your rewards enter the pack when victory is decided. Claiming them closes the result.'],
        ['tip','Armor cannot make you invulnerable. Even its finest protection leaves a little room for pain.'],
        ['tip','A Lucky Coin improves your odds, but cannot make a fifty-percent blow certain.'],
        ['tip','An upgrade needs ingots and a moment outside battle. No distant forge has to grant permission.'],
        ['rambling','The dark has been wearing my late neighbor’s voice. Its impression is dreadful.'],
        ['rambling','There are stars below us. I hear them scratching when the stones are quiet.'],
        ['rambling','I dreamt this road before it broke. The dream has begun sending corrections.'],
        ['rambling','That red mist is a thought someone refused to finish. I would leave it unfinished, too.'],
        ['rambling','The trees have forgotten their names. I am not volunteering to remind them.'],
        ['gruff','Do not ask whether I am frightened. Ask whether it has stopped me.'],
        ['gruff','I have no map to salvation. Try the ordinary map first.'],
        ['gruff','If the realm wanted my opinion, it should have stayed quiet long enough to hear it.'],
        ['gruff','You are the third person to call this place ominous. An observation is not a conversation.'],
        ['gruff','Let an old soul brood in peace. I have earned a little theatrical gloom.']
      ],
      attacked:[
        ['angry','Slow hands, quick temper. A tiresome combination.'],
        ['angry','I was stepping aside from fools before your weapon was ore.'],
        ['angry','That is not how one requests a blessing.'],
        ['angry','Do you strike every question you cannot answer?'],
        ['angry','You have confused an old body with an easy target.'],
        ['angry','Mind the coat. It has survived better villains than you.'],
        ['angry','A lifetime of advice, and apparently I must begin with do not swing at people.'],
        ['angry','I would curse you, but your judgment seems to have beaten me to it.'],
        ['angry','Put it down. I am too old to be impressed and too busy to be dead.'],
        ['angry','Go practice restraint. Your other techniques are not improving the day.']
      ]
    }
  };
  const pools=Object.fromEntries(Object.entries(raw).map(([type,contexts])=>[type,Object.fromEntries(Object.entries(contexts).map(([context,lines])=>[context,lines.map(([tone,text],i)=>({id:`${type}.${context}.${i+1}`,tone,text}))]))]));
  function choose(type,context,previousId){
    const pool=pools[type]?.[context];if(!pool)throw new Error('Unknown NPC dialogue pool');
    return OR.content.pick(pool.filter(line=>line.id!==previousId));
  }
  return {pools,choose};
})();
