'use strict';
OR.finale=(()=>{
 const S=OR.state,W=OR.world,C=OR.content;
 const data=()=>S.data?.finale;
 const active=()=>!!data()&&data().stage!=='done';
 const stages=['intro','book','hunt','gate','ending','done'];
 function valid(s){const f=s.finale;if(f===undefined||f===null)return true;if(!f||typeof f!=='object'||!stages.includes(f.stage)||!Array.isArray(f.route)||f.route.length!==11||typeof f.veilbreaker!=='boolean'||!s.quests?.completed?.includes('hollowflame')||(f.stage!=='done'&&(s.traveler||s.siren||s.pursuit||s.quests?.active||s.quests?.offer)))return false;if(new Set(f.route.map(p=>p&&p.x+','+p.y)).size!==11)return false;if(!f.route.every((p,i)=>p&&Number.isSafeInteger(p.x)&&Number.isSafeInteger(p.y)&&s.blocks?.some(b=>b.x===p.x&&b.y===p.y)&&(i===0||Math.abs(p.x-f.route[i-1].x)+Math.abs(p.y-f.route[i-1].y)===1)))return false;return !['gate','ending','done'].includes(f.stage)||f.veilbreaker;}
 function ensure(){const s=S.data;if(!s||s.finale||!s.quests?.completed?.includes('hollowflame')||s.battle||s.outcome||s.foundLoot||s.traveler||s.siren||s.pursuit||s.quests?.active||s.quests?.offer)return false;
  let route=null;const dirs=[[1,0],[-1,0],[0,1],[0,-1]].sort((a,b)=>(s.x*b[0]+s.y*b[1])-(s.x*a[0]+s.y*a[1]));
  for(let distance=5;distance<=200&&!route;distance++)for(const [dx,dy] of dirs){const line=Array.from({length:11},(_,i)=>({x:s.x+dx*(distance+i),y:s.y+dy*(distance+i)}));if(line.every(p=>Math.max(Math.abs(p.x),Math.abs(p.y))>=W.radius()+8&&!W.at(p.x,p.y)&&!OR.village.template(p.x,p.y))){route=line;break;}}
  if(!route)return false;const guards=['skeleton','undead-knight','troll','undead-knight','gargoyle','ogre'];s.finale={stage:'intro',route,veilbreaker:false};route.forEach((p,i)=>s.blocks.push({...p,elementType:i>0&&i<7?(i===1?'Danger':'Enemy'):'Thing',subtype:i===0?'veil-grimoire':i<7?guards[i-1]:i===7?'vaelric-refuge':i===10?'veil-gate':'clearing',finaleTile:true,resolved:false,...(i===8||i===9?{elementType:'Nature'}:{})}));S.log('Grandfather: You have ended what ended me. But look at the sky. The Cinderseam remains. Follow my light.');S.save();return true;
 }
 const at=i=>{const p=data()?.route[i];return p&&S.data.x===p.x&&S.data.y===p.y;};
 function target(){const f=data();if(!f)return null;if(['intro','book'].includes(f.stage))return f.route[0];if(f.stage==='hunt'){for(let i=1;i<=6;i++)if(!W.at(f.route[i].x,f.route[i].y)?.cleared)return f.route[i];return f.route[7];}if(f.stage==='gate')return f.route[10];return null;}
 function hints(){const p=target(),s=S.data;return p?[...(p.x<s.x?['W']:p.x>s.x?['E']:[]),...(p.y<s.y?['N']:p.y>s.y?['S']:[])]:[];}
 const status=()=>{const p=target();return p?'THE CINDERSEAM REMAINS · '+W.coords(p.x,p.y):'';};
 function guardRemaining(){return data()?.route.slice(1,7).some(p=>!W.at(p.x,p.y)?.cleared);}
 function prompt(b){const f=data();if(!f||f.stage==='done')return null;const act=(label,action)=>({label,action,disabled:false});if(b.subtype==='veil-grimoire'&&f.stage==='book')return act('EXAMINE THE GRIMOIRE','finale:open');if(b.subtype==='vaelric-refuge'&&f.stage==='hunt')return act('SPEAK TO SERETH VENN','finale:open');if(b.subtype==='veil-gate'&&f.stage==='gate')return act('ENTER THE CINDERSEAM','finale:open');return null;}
 function words(){const f=data();if(f.stage==='intro')return {title:'THE CINDERSEAM REMAINS',speaker:'YOUR GRANDFATHER',art:'grandfather-vision',text:'You have ended what ended me. But look at the sky. The Cinderseam remains. Rauthkell guarded a knowledge older than our village. Follow my light. Find the book.',label:'FOLLOW THE GOLDEN LIGHT',action:'finale:begin'};if(f.stage==='ending')return {title:'STRONGWOOD ENDURES',speaker:'YOUR GRANDFATHER',art:'strongwood-dawn',text:'The red sky breaks. Smoke lifts from the road you made safe. The watchpost stores and recovered provisions feed the village. Lanterns burn in open windows again. You finished my battle, then went where I could not. The living have their tomorrow. Now, my child, I can rest.',label:'RETURN HOME',action:'finale:home'};if(at(0))return {title:'THE CINDERSEAM GRIMOIRE',speaker:'WORDS WITHOUT A VOICE',art:'veil-grimoire',text:'You turn the brittle pages. The writing shifts beneath your fingers. You cannot read it. On the cover: the same mark worn by Sereth Venn, the wizard who first enchanted your weapon. Grandfather’s light bends toward his refuge, deep beyond the ash. Taking this book will draw its keeper’s eye.',label:'TAKE THE GRIMOIRE',action:'finale:take'};if(at(7))return {title:'SERETH VENN, THE ASHEN SAGE',speaker:'SERETH VENN',art:'vaelric-refuge',text:guardRemaining()?'Ordrath’s hunters still hold the road. Break their watch, then bring me the book. My ward can hide us, but it cannot close the Cinderseam.':'I left Strongwood to learn what held the Cinderseam open. You have brought the answer. Ordrath is its anchor. His dragon is dead, and now he knows you are coming. Let me bind Strongwood’s Oath into your weapon. Every strike will carry its light. You will need no crystal for this gift. Then end his hold on our home.',label:guardRemaining()?'RETURN TO THE ROAD':'ACCEPT STRONGWOOD’S OATH',action:guardRemaining()?'route:explore':'finale:bless'};return {title:'ORDRATH, LORD OF THE CINDERSEAM',speaker:'BEYOND THE GATE',art:'malrec',text:'The road ends at a gate of black iron. Beyond it, Ordrath waits. Your weapon answers with a steady golden light. Enter when you are ready.',label:'FACE ORDRATH',action:'finale:fight'};}
 function act(action){const s=S.data,f=data();if(!f||s.battle||s.outcome||s.foundLoot)return false;if(action==='begin'&&f.stage==='intro')f.stage='book';else if(action==='take'&&f.stage==='book'&&at(0)){f.stage='hunt';S.add('VeilboundGrimoire',1);S.log('The grimoire is yours. Something beyond the clouds has noticed you. The hunt begins. Six guards stand between you and Sereth Venn.');}else if(action==='bless'&&f.stage==='hunt'&&at(7)&&!guardRemaining()){f.stage='gate';f.veilbreaker=true;S.add('VeilboundGrimoire',-1);s.weapon.basePower+=8;s.hp.current=s.hp.max;s.poisoned=null;S.log('Sereth Venn binds Strongwood’s Oath to your '+s.weapon.type+'. +8 power. Health restored. No crystal is needed for its light.');}else if(action==='fight'&&f.stage==='gate'&&at(10)){Object.assign(W.current(),{elementType:'Enemy',subtype:'malrec',resolved:false});S.save();return OR.combat.start();}else if(action==='home'&&f.stage==='ending'){f.stage='done';s.hope=100;s.x=0;s.y=0;W.current();s.hp.current=s.hp.max;s.poisoned=null;S.log('STRONGWOOD ENDURES. The Cinderseam is closed. Grandfather rests. Your path is your own.');}else return false;S.save();return true;}
 function won(b){const f=data();if(f&&b.subtype==='malrec'){f.stage='ending';OR.analytics?.track('game_completed');S.changeHope(20);S.log('Ordrath falls. The Cinderseam tears open to the dawn.');}}
 return {data,active,valid,ensure,at,target,hints,status,prompt,words,act,won,guardRemaining};
})();
