'use strict';
OR.quests=(()=>{
  const S=OR.state,C=OR.content,W=OR.world;
  const definitions={
    keepsake:{title:'THE BURIED KEEPSAKE',event:'dig',type:'BuriedItems',subtype:'dig',words:'I left a small wooden guardian behind before my last battle. The earth has covered it. Follow my light, dig carefully, and bring that memory back into the world.',reward:[{type:'Potion',qty:1},{type:'SteelIngot',qty:2}],done:'You found my keepsake. Some part of that old life has found its way home.'},
    watchpost:{title:'THE SEALED WATCHPOST',event:'puzzle',type:'Puzzle',words:'We sealed supplies away when the darkness came. Reach the old watchpost, read its inscription, and open the chamber. Strongwood needs what we left there.',reward:[{type:'MetalIngot',qty:3},{type:'Potion',qty:1}],done:'Those supplies will serve the living now. You have given Strongwood a little breathing room.'},
    provisions:{title:'THE MISSING PROVISIONS',event:'chest',type:'LockedItem',subtype:'chest',words:'A supply chest never reached the village. I kept its key. Now you know what it opens. Accept, and I will place it in your hand. Follow my light and recover the provisions.',reward:[{type:'Potion',qty:2},{type:'SteelIngot',qty:2}],done:'The provisions are recovered. Fewer of our people will face the road unprepared.'},
    roadkeeper:{title:'THE ROADKEEPER’S BANE',event:'slay',type:'Enemy',subtype:'ogre',name:'The Roadkeeper’s Bane',words:'An ogre has claimed a road our people once trusted. Follow my light and defeat it. A bribe will not make this road safe. It will strike first when you enter battle.',reward:[{type:'MetalIngot',qty:3},{type:'MagicCrystal',qty:1}],done:'That road belongs to our people again. Your courage has made a real patch of safety.'},
    hollowflame:{title:'WHAT I COULD NOT STOP',event:'slay',type:'Dragon',subtype:'dragon',name:'Hollowflame',words:'Hollowflame is the dragon that killed me. I could not stop it. You have already helped the village in ways I never had the chance to. If you choose this fight, follow my light. It strikes first. If you must flee, its wounds remain, and my light will follow it. End this threat for the living, not for my pride.',reward:[{type:'MetalIngot',qty:5},{type:'SteelIngot',qty:5},{type:'MagicCrystal',qty:2}],done:'Hollowflame is gone. You have ended what I could not. Strongwood can face tomorrow without its shadow. I am proud of you.'}
  };
  const data=()=>S.data.quests||(S.data.quests={completed:[],active:null,offer:null,notice:null});
  const deep=(x,y)=>Math.max(Math.abs(x),Math.abs(y))>=31;
  const eligible=()=>{const q=data();return Object.keys(definitions).filter(id=>!q.completed.includes(id)&&(id!=='hollowflame'||q.completed.length>=4));};
  function migrate(){const q=data();if(!Array.isArray(q.completed))q.completed=[];if(q.keyMigration)return;for(const b of S.data.blocks)if(b.elementType==='LockedItem'&&!b.questId){b.elementType='Thing';b.subtype='empty-chest';b.resolved=true;}if(S.qty('Key')&&!q.active){const n=S.qty('Key');S.add('Key',-n);S.add('SteelIngot',n);}for(const rewards of [S.data.foundLoot?.rewards,S.data.outcome?.rewards,...S.data.blocks.map(b=>b.puzzle?.rewards)])for(const r of rewards||[])if(r.type==='Key')r.type='SteelIngot';q.keyMigration=true;}
  function roll(x,y){if(S.data.pursuit)return null;if(S.data.level<3||!deep(x,y))return null;const q=data();if(q.active||q.offer||!eligible().length||Math.random()>=.01)return null;const id=C.pick(eligible());q.offer={id,x,y,declined:false};return {x,y,elementType:'Quest',subtype:'grandfather-echo',questOffer:id,resolved:false};}
  const offerHere=()=>{const o=data().offer;return o&&S.data.level>=3&&o.x===S.data.x&&o.y===S.data.y?o:null;};
  const showOffer=()=>!!offerHere()&&!offerHere().declined;
  function open(){const o=offerHere();if(!o||data().active)return false;o.declined=false;S.save();return true;}
  function decline(){const o=offerHere();if(!o)return false;o.declined=true;S.save();return true;}
  function destination(){const s=S.data;const valid=(x,y)=>deep(x,y)&&!W.at(x,y)&&!OR.village.template(x,y);for(let i=0;i<200;i++){const dx=C.random(-14,14),dy=C.random(-14,14),distance=Math.abs(dx)+Math.abs(dy);if(distance>=8&&distance<=20&&valid(s.x+dx,s.y+dy))return {x:s.x+dx,y:s.y+dy};}for(let r=8;r<=100;r++)for(let dx=-r;dx<=r;dx++){const dy=r-Math.abs(dx);for(const sign of [-1,1])if(valid(s.x+dx,s.y+sign*dy))return {x:s.x+dx,y:s.y+sign*dy};}return null;}
  function accept(){if(S.data.pursuit)return false;const q=data(),o=offerHere();if(!o||q.active||q.completed.includes(o.id)||!eligible().includes(o.id)||S.data.battle||S.data.outcome||S.data.foundLoot)return false;const to=destination();if(!to)return false;const d=definitions[o.id],subtype=d.subtype||C.pick(['puzzle-plate','puzzle-runes','puzzle-levers']);const b={...to,elementType:d.type,subtype,questId:o.id,resolved:false};if(d.type==='Puzzle'){const unique=OR.puzzles.unique(true);if(unique)Object.assign(b,unique);else{const existing=S.data.blocks.find(t=>t.elementType==='Puzzle'&&!t.questId&&!t.puzzle?.claimed)||S.data.blocks.find(t=>t.elementType==='Puzzle'&&!t.questId);if(!existing)return false;Object.assign(b,existing,{questId:o.id});Object.assign(to,{x:b.x,y:b.y});}}if(d.type==='Dragon'){b.dragonHp=350;b.dragonMaxHp=350;}const prior=W.at(b.x,b.y);if(prior)Object.assign(prior,b);else S.data.blocks.push(b);q.active={id:o.id,...to};const origin=W.at(o.x,o.y);Object.assign(origin,{elementType:'Nature',subtype:'clearing',resolved:true});delete origin.questOffer;q.offer=null;if(d.type==='LockedItem')S.add('Key',1);S.log(d.title+' accepted. Follow the golden compass light to '+W.coords(to.x,to.y)+'.'+(d.type==='LockedItem'?' Grandfather gives you the provisions key.':''));if(d.type==='Puzzle'&&b.puzzle?.claimed)complete('puzzle',b);S.save();return true;}
  const atTarget=b=>{const a=data().active;return !!a&&b?.questId===a.id&&b.x===a.x&&b.y===a.y;};
  function complete(event,b){const q=data(),a=q.active;if(!a||!atTarget(b)||definitions[a.id].event!==event)return false;const d=definitions[a.id];q.completed.push(a.id);S.remember();for(const r of d.reward)S.add(r.type,r.qty);q.notice={title:d.title,words:d.done,rewards:d.reward};q.active=null;delete b.questId;S.log('Grandfather: '+d.done);S.save();return true;}
  function relocate(b,x,y){if(atTarget(b)){data().active.x=x;data().active.y=y;}}
  function hints(){const a=data().active;if(!a)return [];const s=S.data,result=[];if(s.x<a.x)result.push('E');if(s.x>a.x)result.push('W');if(s.y<a.y)result.push('S');if(s.y>a.y)result.push('N');return result;}
  function description(b){if(b.elementType==='Quest')return 'Your grandfather’s voice lingers here. A task remains yours to choose.';if(atTarget(b))return definitions[data().active.id].title+' · Your grandfather’s light leads here.';return null;}
  const name=b=>atTarget(b)?definitions[data().active.id].name:null;
  function takeNotice(){if(!data().notice||S.data.battle||S.data.outcome||S.data.foundLoot)return null;const n=data().notice;data().notice=null;S.save();return n;}
  return {definitions,data,deep,eligible,migrate,roll,offerHere,showOffer,open,decline,accept,atTarget,complete,relocate,hints,description,name,takeNotice};
})();
