const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const root=fs.existsSync(path.resolve(__dirname,'../index.html'))?path.resolve(__dirname,'..'):path.resolve(__dirname,'../outputs/ominous-realms');
function game(storage=new Map(),ui=false){
  function mockNode(){let html='';return {children:[],className:'',hidden:false,classList:{add(){},remove(){}},
    get innerHTML(){return html+this.children.map(n=>'<div class="'+n.className+'">'+n.innerHTML+'</div>').join('');},
    set innerHTML(value){html=value;this.children=[];},appendChild(node){node.parent=this;this.children.push(node);},
    remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);},
    focus(){},addEventListener(){},showModal(){},close(){},querySelector(){return {focus(){}};}};}
  const nodes=Object.fromEntries(['hud','stage','nav','modal','toast','combat-toasts'].map(id=>[id,mockNode()]));
  const ctx={console,Math:Object.create(Math),localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},setInterval:()=>1,clearInterval(){},setTimeout:()=>1,clearTimeout,matchMedia:()=>({matches:true}),scrollY:0,scrollTo(){},history:{pushState(){},replaceState(){}},location:{hash:''},addEventListener(){},document:{createElement:mockNode,getElementById:id=>nodes[id],querySelector:()=>null,addEventListener(){},body:{classList:{toggle(){}}}}};
  ctx.window=ctx;vm.createContext(ctx);
  for(const file of ['content','dialogue','state','world','combat','actions',...(ui?['ui']:[])])vm.runInContext(fs.readFileSync(path.join(root,'js',file+'.js'),'utf8'),ctx,{filename:file+'.js'});
  const g=ctx.OR;g.state.create('Rowan','Sword');g.world.current();g.state.save();
  return {...g,storage,ctx,nodes,rng:n=>ctx.Math.random=()=>n,place:(type,subtype,x=3,y=3)=>{g.state.data.x=x;g.state.data.y=y;let b=g.world.at(x,y);if(!b){b={x,y};g.state.data.blocks.push(b);}Object.assign(b,{elementType:type,subtype,resolved:false});return b;}};
}
test('embark defaults and save schema',()=>{const g=game();const s=g.state.data;assert.equal(s.name,'Rowan');assert.equal(s.hp.current,50);assert.equal(s.armor.resistance,10);assert.equal(s.weapon.moves.length,4);assert.equal(s.weapon.moves[0].accuracy,99);assert.equal(JSON.parse(g.storage.get(g.state.KEY)).version,1);});
test('home and all eight front-yard coordinates are stable',()=>{const g=game();const b=g.world.current();assert.equal(b.elementType,'Home');for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)if(x||y)assert.equal(g.world.getOrCreateBlock(x,y).elementType,'NPC');assert.equal(g.world.current(),b);assert.equal(g.state.data.blocks.length,9);});
test('compass uses correct axes and last heading',()=>{const g=game();for(const d of ['N','E','S','W'])assert.ok(g.world.move(d));assert.equal(g.state.data.x,0);assert.equal(g.state.data.y,0);assert.equal(g.state.data.direction,'W');assert.equal(g.state.data.steps,4);});
test('realm and border include negative coordinates',()=>{const g=game();assert.ok(g.world.local(25,-25));assert.ok(!g.world.local(26,0));assert.ok(!g.world.local(0,-26));assert.ok(g.world.border(-26,50));assert.ok(!g.world.border(27,27));});
test('local generation excludes outer-only elements',()=>{const g=game();for(let x=-25;x<=25;x++)for(let y=-25;y<=25;y++){const b=g.world.getOrCreateBlock(x,y);assert.ok(!g.content.outerOnly.includes(b.elementType));}});
test('critical health finds a potion on the next step without replacing the tile',()=>{const g=game();g.state.data.hp.current=10;g.rng(.99);g.world.move('N');assert.equal(g.state.qty('Potion'),1);assert.equal(g.world.current().elementType,'NPC');assert.equal(g.state.data.hp.current,10);assert.equal(g.state.data.lastFind.type,'Potion');g.state.load();assert.equal(g.state.qty('Potion'),1);assert.equal(g.state.data.lastFind.y,-1);});
test('low-health healing is guaranteed by three steps even on previously explored paths',()=>{const g=game();g.state.data.hp.current=25;g.rng(.99);g.world.move('N');assert.equal(g.state.qty('Potion'),0);g.state.load();g.world.move('S');assert.equal(g.state.qty('Potion'),0);g.world.move('N');assert.equal(g.state.qty('Potion'),1);assert.equal(g.state.data.healingSearchSteps,0);assert.equal(g.world.current().elementType,'NPC');});
test('walking never grants extra potions when healthy or already carrying one',()=>{const g=game();g.rng(0);for(let i=0;i<8;i++)g.world.move('N');assert.equal(g.state.qty('Potion'),0);g.state.data.hp.current=10;g.state.add('Potion');for(let i=0;i<8;i++)g.world.move('S');assert.equal(g.state.qty('Potion'),1);assert.equal(g.state.data.lastFind,null);});
test('walking cannot grant healing during battle and does not erase a dragon',()=>{const g=game();const b=g.place('Dragon','dragon',27,0);b.dragonHp=600;g.combat.start();g.state.data.hp.current=10;assert.equal(g.world.move('N'),false);assert.equal(g.state.qty('Potion'),0);g.combat.flee();g.place('Nature','forest',27,1);g.rng(.99);g.world.move('N');assert.equal(g.world.current().elementType,'Dragon');assert.equal(g.world.current().dragonHp,600);assert.equal(g.state.qty('Potion'),1);});
test('mushrooms spawn in Strongwood and heal without leaving the village',()=>{const g=game();g.rng(.5);const b=g.world.getOrCreateBlock(5,5);assert.equal(b.elementType,'Food');assert.equal(b.subtype,'mushrooms');g.state.data.x=5;g.state.data.y=5;g.state.data.hp.current=1;g.actions.eat();assert.equal(g.state.data.hp.current,50);});
test('walking pickup shows potion card and toast, then full healing clears the find',()=>{const g=game(new Map(),true);g.state.data.hp.current=10;g.ui.dispatch('move:N');assert.match(g.nodes.stage.innerHTML,/HEALING FOUND/);assert.match(g.nodes.stage.innerHTML,/DRINK POTION/);assert.match(g.nodes.toast.innerHTML,/POTION FOUND/);g.ui.dispatch('potion');assert.equal(g.state.data.hp.current,50);assert.equal(g.state.qty('Potion'),0);assert.equal(g.state.data.lastFind,null);assert.ok(!g.nodes.stage.innerHTML.includes('HEALING FOUND'));});
test('Nature revisits become Danger locally and can become Enemy outside',()=>{const g=game();g.place('Nature','forest',3,3);g.rng(.9);assert.equal(g.world.getOrCreateBlock(3,3,true).elementType,'Danger');g.place('Nature','forest',27,0);assert.equal(g.world.getOrCreateBlock(27,0,true).elementType,'Enemy');});
test('damage honors power, armor, misses and Lucky Coin accuracy',()=>{const g=game();g.rng(.91);const m={power:5,accuracy:90};assert.equal(g.combat.damage(5,m,10),0);assert.equal(g.combat.damage(5,m,10,true),9);g.rng(.9999);assert.equal(g.combat.damage(5,{power:0,accuracy:100},0),5);});
test('win clears coordinate, rewards once, and persists outcome',()=>{const g=game();g.rng(0);g.place('Danger','snake');g.combat.start();g.state.data.battle.enemy.hp=1;g.combat.attack(1);assert.equal(g.state.data.victories,1);assert.equal(g.world.current().elementType,'Nature');assert.equal(g.state.data.battle,null);assert.ok(g.state.data.outcome.win);const count=g.state.data.inventory.reduce((n,i)=>n+i.qty,0);assert.equal(count,1);g.state.load();assert.ok(g.state.data.outcome);g.combat.claim();g.combat.claim();assert.equal(g.state.data.inventory.reduce((n,i)=>n+i.qty,0),count);});
test('unconsciousness floors health at 1 without erasing the warrior',()=>{const g=game();g.place('Enemy','ogre',27,0);g.combat.start();g.state.data.battle.enemy.basePower=1000;g.state.data.battle.enemy.hp=1000;g.rng(0);g.combat.attack(0);assert.equal(g.state.data.hp.current,1);assert.equal(g.state.data.outcome.win,false);assert.equal(g.state.data.victories,0);assert.equal(g.world.current().elementType,'Home');assert.equal(g.world.at(27,0).elementType,'Enemy');assert.equal(g.state.data.x,0);assert.equal(g.state.data.y,0);});
test('magic is locked without crystal and consumed on use',()=>{const g=game();g.place('Danger','skeleton');g.combat.start();assert.equal(g.combat.attack(3),false);g.state.add('MagicCrystal');g.rng(0);assert.ok(g.combat.attack(3));assert.equal(g.state.qty('MagicCrystal'),0);});
test('level five-win threshold improves gear, max health, and heals',()=>{const g=game();g.state.data.victories=5;g.state.data.hp.current=12;assert.equal(g.combat.levelUp(),1);assert.equal(g.state.data.level,2);assert.equal(g.state.data.hp.max,58);assert.equal(g.state.data.hp.current,58);assert.equal(g.state.data.weapon.basePower,6);assert.equal(g.state.data.armor.resistance,11);assert.equal(g.combat.levelUp(),0);});
test('dragon damage survives flee, revisits, and reload',()=>{const g=game();g.rng(0);const b=g.place('Dragon','dragon',27,0);b.dragonHp=500;g.combat.start();g.combat.attack(1);const hp=b.dragonHp;assert.ok(hp<500);g.combat.flee();g.state.load();g.combat.start();assert.equal(g.state.data.battle.enemy.hp,hp);assert.equal(g.state.data.battle.enemy.maxHp,500);});
test('bribe costs one gem, wins and removes enemy',()=>{const g=game();g.place('Enemy','troll',27,0);g.combat.start();assert.equal(g.combat.bribe(),false);g.state.add('Gem');g.rng(0);assert.ok(g.combat.bribe());assert.equal(g.state.qty('Gem'),0);assert.equal(g.state.data.victories,1);assert.equal(g.world.current().elementType,'Nature');});
test('dragon slain produces two large rewards and remains removed',()=>{const g=game();g.rng(0);const b=g.place('Dragon','dragon',27,0);b.dragonHp=1;g.combat.start();g.combat.attack(1);assert.equal(g.state.data.outcome.dragon,true);assert.equal(g.state.data.outcome.rewards.length,2);assert.ok(g.state.data.outcome.rewards.every(r=>r.qty>=3));assert.equal(g.world.current().dragonHp,null);});
test('active battle is serialized and movement is blocked',()=>{const g=game();g.place('Enemy','gargoyle',27,0);g.combat.start();const hp=g.state.data.battle.enemy.hp;assert.equal(g.world.move('N'),false);g.state.load();assert.equal(g.state.data.battle.enemy.hp,hp);assert.equal(g.state.data.x,27);});
test('food heals wounded warrior but poisons a full warrior',()=>{const g=game();g.rng(.99);g.place('Food','mushrooms',27,0);g.state.data.hp.current=3;g.actions.eat();assert.equal(g.state.data.hp.current,50);g.place('Food','mushrooms',28,0);g.actions.eat();assert.equal(g.state.data.hp.current,47);assert.equal(g.world.current().elementType,'Nature');});
test('digging spends health per foot and rewards only a completed dig',()=>{const g=game();g.rng(0);g.place('BuriedItems','dig');g.actions.dig();assert.equal(g.world.current().digDepth,3);assert.equal(g.state.data.hp.current,49);assert.equal(g.state.data.inventory.length,0);g.actions.dig();g.actions.dig();assert.equal(g.state.data.hp.current,47);assert.equal(g.world.current().elementType,'Nature');assert.equal(g.state.data.inventory.length,0);assert.equal(g.state.data.foundLoot.rewards.length,1);g.actions.gatherLoot();assert.equal(g.state.data.inventory.length,1);});
test('failed dig never rewards or kills',()=>{const g=game();g.place('BuriedItems','dig');g.rng(.99);g.state.data.hp.current=2;g.actions.dig();assert.equal(g.state.data.hp.current,1);assert.equal(g.state.data.inventory.length,0);assert.equal(g.actions.dig(),false);});
test('chest requires and consumes key once',()=>{const g=game();g.place('LockedItem','chest',27,0);assert.equal(g.actions.unlock(),false);g.state.add('Key');g.rng(0);g.actions.unlock();assert.equal(g.state.qty('Key'),0);assert.equal(g.world.current().elementType,'Nature');assert.equal(g.actions.unlock(),false);});
test('NPC attacks are dodged; talk resolves without damage',()=>{const g=game();g.place('NPC','villager');g.actions.talk(true);assert.equal(g.state.data.hp.current,50);assert.match(g.state.data.message,/move beyond your reach/);assert.equal(g.world.current().resolved,true);});
test('upgrades work away from forges with exact increasing material costs',()=>{const g=game();g.state.add('MetalIngot',25);g.state.add('SteelIngot',20);g.place('Nature','forest');assert.equal(g.actions.craft('armor'),true);assert.equal(g.state.qty('MetalIngot'),15);assert.equal(g.actions.armorCost(),11);assert.equal(g.actions.craft('weapon'),true);assert.equal(g.state.qty('SteelIngot'),14);assert.equal(g.actions.weaponCost(),7);});
test('potions heal fully and cannot be wasted at full health',()=>{const g=game();g.state.add('Potion',2);assert.equal(g.actions.potion(),false);g.state.data.hp.current=1;assert.equal(g.actions.potion(),true);assert.equal(g.state.data.hp.current,50);assert.equal(g.state.qty('Potion'),1);});
test('injury biases Potion and unique relics never duplicate',()=>{const g=game();g.state.data.hp.current=20;g.rng(.2);assert.equal(g.state.loot(),'Potion');g.state.add('MagicCrystal');g.state.add('LuckyCoin');for(let i=0;i<101;i++){g.rng(i/101);assert.ok(!['MagicCrystal','LuckyCoin'].includes(g.state.loot()));}});
test('journal retains last 50 and reset removes only game save',()=>{const g=game();for(let i=0;i<70;i++)g.state.log('line '+i);assert.equal(g.state.data.journal.length,50);assert.equal(g.state.data.journal[0],'line 20');g.storage.set('unrelated','keep');g.state.reset();assert.equal(g.storage.get('unrelated'),'keep');assert.equal(g.storage.has(g.state.KEY),false);});
test('bad saves are preserved and reported without crashing',()=>{const g=game();g.storage.set(g.state.KEY,'{bad');assert.equal(g.state.load(),null);assert.ok(g.state.error);assert.equal(g.storage.get(g.state.KEY),'{bad');g.storage.set(g.state.KEY,JSON.stringify({version:99}));assert.equal(g.state.load(),null);});
test('storage errors return false and expose a warning',()=>{const g=game();g.ctx.localStorage.setItem=()=>{throw Error('quota');};assert.equal(g.state.save(),false);assert.match(g.state.error,/not saved/);});
test('all player screens render; HUD and navigation remain after embark',()=>{const g=game(new Map(),true);g.ui.init();assert.equal(g.ui.screen,'explore');for(const page of ['title','explore','encounter','pack','forge','map','hero','journal']){g.ui.route(page);assert.ok(g.nodes.stage.innerHTML.length>100,page);assert.ok(!g.nodes.stage.innerHTML.includes('undefined'),page);assert.equal(g.nodes.hud.hidden,false,page);assert.equal(g.nodes.nav.hidden,false,page);}assert.equal((g.nodes.stage.innerHTML.match(/journal-list/g)||[]).length,1);g.ui.route('title');assert.match(g.nodes.stage.innerHTML,/CONTINUE JOURNEY/);});
test('battle and aftermath screens preserve HUD; reload lands on Explore',()=>{const g=game(new Map(),true);g.place('Danger','snake');g.combat.start();g.ui.route('battle');assert.match(g.nodes.stage.innerHTML,/ROUND 01/);g.ui.init();assert.equal(g.ui.screen,'explore');assert.match(g.nodes.stage.innerHTML,/RESUME BATTLE/);g.state.data.battle.enemy.hp=1;g.rng(0);g.combat.attack(0);g.ui.route('aftermath');assert.match(g.nodes.stage.innerHTML,/YOU WIN/);assert.equal(g.nodes.hud.hidden,false);});
test('new player onboarding supports every weapon and name screen',()=>{const g=game(new Map(),true);g.state.reset();g.ui.init();assert.equal(g.ui.screen,'title');assert.equal(g.nodes.hud.hidden,true);g.ui.dispatch('embark');assert.match(g.nodes.stage.innerHTML,/ACCEPT ARMOR/);g.ui.dispatch('accept-armor');for(const type of Object.keys(g.content.weapons)){g.ui.dispatch('choose:'+type);assert.match(g.nodes.stage.innerHTML,new RegExp('TAKE THE '+type.toUpperCase()));}g.ui.dispatch('accept-weapon');assert.match(g.nodes.stage.innerHTML,/name-form/);assert.match(g.nodes.stage.innerHTML,/warrior-knife/);});
test('map renders exactly 121 cells and every entity selects realm-specific art',()=>{const g=game(new Map(),true);g.ui.route('map');assert.equal((g.nodes.stage.innerHTML.match(/role="gridcell"/g)||[]).length,121);for(const e of Object.values(g.content.entities)){for(const outer of [false,true]){g.place(e.type,e.id,outer?27:3,3);g.ui.route('encounter');assert.ok(!g.nodes.stage.innerHTML.includes('undefined'),e.id);const desc=outer?e.outer:e.village;assert.ok(g.nodes.stage.innerHTML.includes(g.ui.escape(desc)),e.id);}}});
test('user-controlled names are escaped in rendered HTML',()=>{const g=game(new Map(),true);g.state.data.name='<img onerror=alert(1)>';g.ui.route('hero');assert.ok(!g.nodes.stage.innerHTML.includes('<img onerror'));assert.match(g.nodes.stage.innerHTML,/&lt;IMG/);});
test('NPC reply replaces scenery in a named speech bubble until conversation ends',()=>{const g=game(new Map(),true);g.place('NPC','woodcutter');g.rng(0);g.ui.route('encounter');assert.match(g.nodes.stage.innerHTML,/freshly cut stump/);assert.ok(!g.nodes.stage.innerHTML.includes('data-typewriter'));g.ui.dispatch('talk');assert.equal(g.ui.screen,'encounter');assert.match(g.nodes.stage.innerHTML,/IN CONVERSATION/);assert.match(g.nodes.stage.innerHTML,/speech-bubble/);assert.match(g.nodes.stage.innerHTML,/THE WOODCUTTER/);assert.match(g.nodes.stage.innerHTML,/data-typewriter/);assert.ok(!g.nodes.stage.innerHTML.includes('freshly cut stump'));assert.ok(!g.nodes.stage.innerHTML.includes('CHOOSE YOUR PATH'));assert.ok(!g.nodes.stage.innerHTML.includes('recent-message'));g.state.load();g.ui.init();assert.match(g.nodes.stage.innerHTML,/END CONVERSATION/);g.ui.dispatch('end-conversation');assert.equal(g.ui.screen,'explore');assert.match(g.nodes.stage.innerHTML,/CHOOSE YOUR PATH/);assert.ok(!g.nodes.stage.innerHTML.includes('speech-bubble'));});
test('elder draws a spoken reply from the new dialogue pool',()=>{const g=game(new Map(),true);g.place('NPC','elder');g.rng(0);g.ui.dispatch('talk');assert.match(g.nodes.stage.innerHTML,/SPEAKING/);assert.match(g.nodes.stage.innerHTML,/Memory has its priorities/);assert.ok(g.nodes.stage.innerHTML.includes('data-typewriter'));});
test('ignoring a revisited NPC does not repeat an earlier conversation',()=>{const g=game(new Map(),true);g.place('NPC','villager');g.actions.talk();g.world.current().resolved=false;g.ui.dispatch('ignore');assert.ok(!g.nodes.stage.innerHTML.includes('speech-bubble'));assert.match(g.nodes.stage.innerHTML,/CHOOSE YOUR PATH/);});
test('speech text types character by character and can be revealed immediately',()=>{const g=game(new Map(),true);g.place('NPC','villager');g.rng(0);let tick,cleared=false,el;const skip={disabled:false},label={textContent:''};const bubble={classList:{add(){},remove(){}},querySelector:s=>s==='.speech-skip'?skip:label,addEventListener(){},removeEventListener(){}};g.ctx.matchMedia=()=>({matches:false});g.ctx.setInterval=(fn,ms)=>{assert.equal(ms,12);tick=fn;return 123;};g.ctx.clearInterval=()=>{cleared=true;};g.ctx.document.querySelector=s=>{if(s!=='[data-typewriter]')return null;el={textContent:g.world.current().dialogue.text,closest:()=>bubble};return el;};g.ui.dispatch('talk');const full=g.world.current().dialogue.text;assert.equal(el.textContent,'');tick();assert.equal(el.textContent,full.slice(0,1));g.ui.dispatch('skip-dialogue');assert.equal(el.textContent,full);assert.equal(cleared,true);assert.equal(skip.disabled,true);assert.equal(label.textContent,'· SAID');});
test('exhaustion while digging returns home without erasing the dig site or granting loot',()=>{const g=game();g.place('BuriedItems','dig',-28,4);g.state.data.hp.current=2;g.rng(.99);g.actions.dig();assert.equal(g.state.data.x,0);assert.equal(g.state.data.y,0);assert.equal(g.state.data.hp.current,1);assert.equal(g.world.current().elementType,'Home');assert.equal(g.world.at(-28,4).elementType,'BuriedItems');assert.equal(g.world.at(-28,4).dug,1);assert.equal(g.state.data.inventory.length,0);});
test('poison sends the player home after consuming mushrooms at the original coordinate',()=>{const g=game();g.place('Food','mushrooms',27,6);g.state.data.level=20;g.rng(.99);g.actions.eat();assert.equal(g.state.data.hp.current,1);assert.equal(g.state.data.x,0);assert.equal(g.state.data.y,0);assert.equal(g.world.at(27,6).elementType,'Nature');assert.equal(g.world.at(0,0).elementType,'Home');});
test('losing to a dragon preserves its wounds, inventory and discoveries across reload',()=>{const g=game();const b=g.place('Dragon','dragon',30,-8);b.dragonHp=500;g.state.add('Gem',3);g.combat.start();g.state.data.battle.enemy.basePower=1000;g.rng(0);g.combat.attack(1);assert.equal(g.state.data.hp.current,1);assert.ok(b.dragonHp<500);const hp=b.dragonHp;assert.equal(g.state.data.outcome.win,false);assert.equal(g.state.data.x,0);assert.equal(g.state.data.y,0);g.state.load();assert.equal(g.world.at(30,-8).dragonHp,hp);assert.equal(g.state.qty('Gem'),3);assert.equal(g.state.data.victories,0);assert.equal(g.state.data.battle,null);});
function gameClock(g,start=1000000){let now=start;g.ctx.Date={now:()=>now};return {advance:ms=>now+=ms,set:ms=>now=ms,get now(){return now;}};}
test('old saves stranded at 1 HP are rescued on boot and recover gradually at home',()=>{const g=game(new Map(),true),clock=gameClock(g);g.place('Danger','snake',-27,2);g.state.data.hp.current=1;g.state.save();g.state.load();g.ui.init();assert.equal(g.state.data.x,0);assert.equal(g.state.data.y,0);assert.equal(g.ui.screen,'explore');assert.match(g.nodes.stage.innerHTML,/10:00/);assert.equal(g.world.move('N'),false);const journalLength=g.state.data.journal.length;g.ui.init();assert.equal(g.state.data.journal.length,journalLength);g.ui.dispatch('rest');assert.equal(g.state.data.hp.current,1);assert.equal(g.state.qty('Potion'),0);clock.advance(600000);g.state.load();assert.equal(g.state.data.hp.current,50);assert.ok(g.world.move('N'));assert.equal(g.state.data.y,-1);});
test('rest cannot be triggered away from home or through an unresolved battle result',()=>{const g=game(),clock=gameClock(g);g.place('Nature','forest',2,2);g.state.data.hp.current=10;assert.equal(g.actions.rest(),false);g.world.returnHome();g.state.data.outcome={win:false,rewards:[]};assert.equal(g.actions.rest(),false);g.combat.claim();assert.ok(g.actions.rest());assert.equal(g.state.data.hp.current,10);clock.advance(600000);g.state.syncRest();assert.equal(g.state.data.hp.current,50);assert.equal(g.actions.rest(),false);});
test('offline home healing is gradual, capped, and cannot be double-counted on reload',()=>{const g=game(),clock=gameClock(g);g.state.data.hp.current=1;g.actions.rest();clock.advance(300000);g.state.load();assert.equal(g.state.data.hp.current,25);g.state.save();g.state.load();assert.equal(g.state.data.hp.current,25);clock.advance(150000);g.state.load();assert.equal(g.state.data.hp.current,37);clock.advance(150000);g.state.load();assert.equal(g.state.data.hp.current,50);assert.equal(g.state.data.rest,null);g.state.save();const lines=g.state.data.journal.length;clock.advance(86400000);g.state.load();assert.equal(g.state.data.hp.current,50);assert.equal(g.state.data.journal.length,lines);});
test('leaving home stops rest and a later return starts a fresh clock',()=>{const g=game(),clock=gameClock(g);g.rng(.99);g.state.data.hp.current=1;g.actions.rest();clock.advance(60000);g.world.move('N');assert.equal(g.state.data.hp.current,5);assert.equal(g.state.data.rest,null);clock.advance(3600000);g.state.load();assert.equal(g.state.data.hp.current,5);g.world.move('S');assert.equal(g.state.data.hp.current,5);assert.equal(g.state.data.rest.startedAt,clock.now);clock.advance(60000);g.state.syncRest();assert.equal(g.state.data.hp.current,9);});
test('time away during battle grants no health and preserves the encounter',()=>{const g=game(),clock=gameClock(g);g.place('Enemy','ogre',27,0);g.state.data.hp.current=10;g.combat.start();const hp=g.state.data.battle.enemy.hp;clock.advance(3600000);g.state.load();assert.equal(g.state.data.hp.current,10);assert.equal(g.state.data.battle.enemy.hp,hp);assert.equal(g.state.data.rest,null);assert.equal(g.state.data.x,27);});
test('potions heal instantly during rest and are not wasted after offline recovery',()=>{const g=game(),clock=gameClock(g);g.state.data.hp.current=1;g.state.add('Potion',2);g.actions.rest();clock.advance(10000);assert.equal(g.actions.potion(),true);assert.equal(g.state.data.hp.current,50);assert.equal(g.state.qty('Potion'),1);assert.equal(g.state.data.rest,null);g.state.data.hp.current=1;g.actions.rest();clock.advance(600000);assert.equal(g.actions.potion(),false);assert.equal(g.state.qty('Potion'),1);assert.equal(JSON.parse(g.storage.get(g.state.KEY)).hp.current,50);});
test('rest scales with maximum health and handles clock rollback without granting health',()=>{const g=game(),clock=gameClock(g);g.state.data.hp.max=200;g.state.data.hp.current=1;g.actions.rest();clock.advance(300000);g.state.syncRest();assert.equal(g.state.data.hp.current,100);clock.advance(300000);g.state.syncRest();assert.equal(g.state.data.hp.current,200);g.state.data.hp.current=10;g.actions.rest();clock.set(100);g.state.syncRest();assert.equal(g.state.data.hp.current,10);assert.equal(g.state.data.rest.startedAt,100);});
test('live home countdown updates and leaving becomes available after the first recovered HP',()=>{const g=game(new Map(),true),clock=gameClock(g);let tick;g.ctx.setInterval=(fn,ms)=>{if(ms===1000)tick=fn;return 1;};g.state.data.hp.current=1;g.ui.init();g.nodes['rest-countdown']={textContent:'10:00'};clock.advance(10000);tick();assert.equal(g.nodes['rest-countdown'].textContent,'9:50');assert.equal(g.state.data.hp.current,1);clock.advance(3000);tick();assert.equal(g.state.data.hp.current,2);assert.match(g.nodes.stage.innerHTML,/Leave whenever you like/);assert.ok(!g.nodes.stage.innerHTML.includes('data-action="move:N" disabled'));clock.advance(600000);tick();assert.equal(g.state.data.hp.current,50);assert.match(g.nodes.toast.innerHTML,/FULLY RESTED/);});
test('hostile tiles offer battle or walking directly without an investigation step',()=>{for(const [type,id] of [['Danger','snake'],['Enemy','ogre'],['Dragon','dragon']]){const g=game(new Map(),true),b=g.place(type,id,27,0);if(type==='Dragon')b.dragonHp=500;g.ui.route('explore');assert.match(g.nodes.stage.innerHTML,/ENTER BATTLE/);assert.match(g.nodes.stage.innerHTML,/KEEP WALKING/);assert.ok(!g.nodes.stage.innerHTML.includes('INVESTIGATE'));g.ui.dispatch('ignore');assert.equal(g.state.data.battle,null);assert.equal(g.state.data.victories,0);assert.match(g.nodes.stage.innerHTML,/CHOOSE YOUR PATH/);b.resolved=false;g.ui.route('explore');g.ui.dispatch('fight');assert.equal(g.ui.screen,'battle');assert.equal(g.state.data.battle.enemyId,id);}});
function roundTimers(g){let next=0;const pending=new Map();g.ctx.setTimeout=(fn,ms)=>{const id=++next;pending.set(id,{fn,ms});return id;};g.ctx.clearTimeout=id=>pending.delete(id);return {beat(){const entry=[...pending].find(([,t])=>t.ms===950);if(entry){pending.delete(entry[0]);entry[1].fn();}},flush(){while([...pending.values()].some(t=>t.ms===950))this.beat();},pending};}
test('completed dig shows saved loot to gather, then announces it exactly once',()=>{const g=game(new Map(),true);g.place('BuriedItems','dig',3,3);g.rng(0);g.ui.route('encounter');g.ui.dispatch('dig');g.ui.dispatch('dig');assert.equal(g.state.data.foundLoot,null);g.ui.dispatch('dig');assert.match(g.nodes.stage.innerHTML,/TREASURE UNEARTHED/);assert.match(g.nodes.stage.innerHTML,/GATHER LOOT/);assert.match(g.nodes.stage.innerHTML,/>Potion</);assert.match(g.nodes.stage.innerHTML,/>\+1</);assert.doesNotMatch(g.nodes.stage.innerHTML,/CHOOSE YOUR PATH/);assert.equal(g.state.qty('Potion'),0);assert.equal(g.world.move('N'),false);const pending=JSON.stringify(g.state.data.foundLoot);g.state.load();g.ui.init();assert.equal(JSON.stringify(g.state.data.foundLoot),pending);assert.match(g.nodes.stage.innerHTML,/GATHER LOOT/);assert.equal(g.actions.dig(),false);g.ui.dispatch('gather-loot');assert.equal(g.state.qty('Potion'),1);assert.equal(g.state.data.foundLoot,null);assert.match(g.nodes.stage.innerHTML,/CHOOSE YOUR PATH/);assert.match(g.nodes.toast.innerHTML,/LOOT GATHERED/);assert.match(g.nodes.toast.innerHTML,/\+1 Potion/);assert.equal(g.nodes.toast.className,'toast-reward');g.ui.dispatch('gather-loot');g.state.load();assert.equal(g.state.qty('Potion'),1);assert.equal(g.state.data.foundLoot,null);});
test('a dig ending in exhaustion never offers treasure or a gather action',()=>{const g=game(new Map(),true);g.place('BuriedItems','dig',3,3);g.state.data.hp.current=2;g.rng(0);g.ui.dispatch('dig');assert.equal(g.world.current().elementType,'Home');assert.equal(g.state.data.foundLoot,null);assert.equal(g.actions.gatherLoot(),false);assert.equal(g.state.data.inventory.length,0);assert.doesNotMatch(g.nodes.stage.innerHTML,/GATHER LOOT|TREASURE UNEARTHED/);});
test('all five NPCs have 25 Strongwood, 25 Outer Realm and 10 attacked lines with unique text',()=>{const g=game(),seen=new Set(),ids=new Set();const types=Object.values(g.content.entities).filter(e=>e.type==='NPC').map(e=>e.id);assert.equal(types.length,5);for(const type of types)for(const [context,count] of [['strongwood',25],['outer',25],['attacked',10]]){const lines=g.dialogue.pools[type][context];assert.equal(lines.length,count,type+'.'+context);for(const line of lines){assert.ok(line.text.trim());assert.ok(!seen.has(line.text),line.text);assert.ok(!ids.has(line.id),line.id);seen.add(line.text);ids.add(line.id);}if(context!=='attacked')for(const [tone,count] of [['life',8],['tip',7],['rambling',5],['gruff',5]])assert.equal(lines.filter(l=>l.tone===tone).length,count);}assert.equal(seen.size,300);});
test('NPC dialogue selects by role and realm, reaches every line, and saves without consecutive repeats',()=>{for(const type of ['villager','farmer','woodcutter','hunter','elder'])for(const context of ['strongwood','outer','attacked']){const g=game();const x=context==='outer'?27:3;const pool=g.dialogue.pools[type][context];for(let i=0;i<pool.length;i++){g.state.data.dialogueLast={};g.place('NPC',type,x,3);g.rng((i+.5)/pool.length);g.actions.talk(context==='attacked');assert.equal(g.world.current().dialogue.id,pool[i].id);assert.equal(g.world.current().dialogue.text,'“'+pool[i].text+'”');assert.equal(g.state.data.hp.current,50);}g.rng(0);g.state.data.dialogueLast={};g.actions.talk(context==='attacked');const first=g.world.current().dialogue.id;g.state.load();g.actions.talk(context==='attacked');assert.notEqual(g.world.current().dialogue.id,first);assert.ok(g.world.current().dialogue.spoken);}});
test('HUD upgrades preserve the encounter and remain blocked in combat or without materials',()=>{const g=game(new Map(),true),b=g.place('Enemy','ogre',27,0);g.state.add('SteelIngot',6);g.ui.route('explore');assert.match(g.nodes.hud.innerHTML,/data-action="forge:weapon"/);assert.match(g.nodes.hud.innerHTML,/data-action="forge:armor"/);g.ui.dispatch('forge:weapon');assert.equal(g.ui.screen,'forge');assert.match(g.nodes.stage.innerHTML,/data-action="craft:weapon" >/);assert.equal(g.actions.craft('armor'),false);g.ui.dispatch('craft:weapon');assert.equal(g.state.data.weapon.basePower,6);assert.equal(g.state.qty('SteelIngot'),0);assert.equal(g.actions.craft('weapon'),false);assert.match(g.nodes.stage.innerHTML,/data-action="route:explore"\s*>KEEP WALKING/);g.ui.dispatch('route:explore');assert.equal(b.resolved,false);assert.match(g.nodes.stage.innerHTML,/ENTER BATTLE/);g.state.add('SteelIngot',20);g.combat.start();assert.equal(g.actions.craft('weapon'),false);g.ui.dispatch('forge:weapon');assert.equal(g.ui.screen,'battle');g.state.data.battle=null;g.state.data.outcome={win:false,rewards:[]};assert.equal(g.actions.craft('weapon'),false);assert.equal(g.state.qty('SteelIngot'),20);});
test('forge offers the other upgrade and a direct way back to walking',()=>{const g=game(new Map(),true);g.place('Craft','forge');g.state.add('MetalIngot',10);g.state.add('SteelIngot',6);g.ui.dispatch('forge:armor');assert.match(g.nodes.stage.innerHTML,/data-action="forge:weapon"/);g.ui.dispatch('craft:armor');assert.equal(g.state.data.armor.resistance,11);assert.match(g.nodes.stage.innerHTML,/data-action="forge:weapon"/);g.ui.dispatch('forge:weapon');assert.equal(g.state.qty('SteelIngot'),6);assert.match(g.nodes.stage.innerHTML,/data-action="forge:armor"/);g.ui.dispatch('craft:weapon');assert.equal(g.state.data.weapon.basePower,6);assert.match(g.nodes.stage.innerHTML,/KEEP WALKING/);g.ui.dispatch('ignore');assert.equal(g.ui.screen,'explore');assert.match(g.nodes.stage.innerHTML,/CHOOSE YOUR PATH/);});
test('combat reveals independent hit and miss rolls on separate beats with matching vitality',()=>{for(const playerMiss of [true,false]){const g=game(new Map(),true),timers=roundTimers(g);g.place('Enemy','ogre',27,0);g.combat.start();g.ui.route('battle');const rolls=playerMiss?[.9999,0,0]:[0,0,.9999];g.ctx.Math.random=()=>rolls.shift()??0;g.ui.dispatch('attack:1');const health=g.state.data.hp.current;assert.match(g.nodes['combat-toasts'].innerHTML,playerMiss?/YOU MISSED/:/YOU HIT/);assert.doesNotMatch(g.nodes.stage.innerHTML,/round-feedback|combat-log/);assert.doesNotMatch(g.nodes['combat-toasts'].innerHTML,/YOU TOOK DAMAGE|ENEMY MISSED/);assert.doesNotMatch(g.nodes.stage.innerHTML,/YOU TOOK DAMAGE|ENEMY MISSED|struck-player/);assert.match(g.nodes.hud.innerHTML,/aria-valuenow="50"/);assert.equal(JSON.parse(g.storage.get(g.state.KEY)).hp.current,health);g.ui.dispatch('attack:1');assert.equal(g.state.data.battle.round,2);timers.beat();assert.match(g.nodes['combat-toasts'].innerHTML,playerMiss?/YOU TOOK DAMAGE/:/ENEMY MISSED/);assert.doesNotMatch(g.nodes.stage.innerHTML,/ENEMY PREPARING|struck-enemy/);assert.equal(g.nodes.hud.innerHTML.includes('vitality-damaged'),playerMiss);g.ui.dispatch('attack:1');assert.equal(g.state.data.battle.round,2);timers.beat();assert.match(g.nodes.stage.innerHTML,/MAKE YOUR MOVE/);assert.equal(g.state.data.hp.current,health);}});
test('poison announces actual health loss and animates vitality without replay on navigation',()=>{const g=game(new Map(),true);g.place('Food','mushrooms',3,3);g.ui.route('encounter');g.rng(.99);const effects=[];g.nodes.stage.classList.add=name=>effects.push(name);g.ui.dispatch('eat');assert.equal(g.state.data.hp.current,47);assert.match(g.nodes.toast.innerHTML,/POISONED · −3 HP/);assert.equal(g.nodes.toast.className,'toast-danger');assert.match(g.nodes.hud.innerHTML,/vitality-damaged/);assert.match(g.nodes.hud.innerHTML,/−3 HP/);assert.match(g.nodes.hud.innerHTML,/--hp-before:100%/);assert.ok(effects.includes('damage-taken'));g.ui.route('pack');assert.doesNotMatch(g.nodes.hud.innerHTML,/vitality-damaged/);assert.equal(effects.length,1);});
test('digging and combat losses animate vitality while healing and loading do not',()=>{const g=game(new Map(),true),timers=roundTimers(g);g.place('BuriedItems','dig',3,3);g.ui.route('encounter');g.rng(0);g.ui.dispatch('dig');assert.match(g.nodes.hud.innerHTML,/−1 HP/);g.state.add('Potion');g.ui.dispatch('potion');assert.doesNotMatch(g.nodes.hud.innerHTML,/vitality-damaged/);g.place('Enemy','ogre',27,0);g.combat.start();g.ui.route('battle');g.ui.dispatch('attack:0');assert.doesNotMatch(g.nodes.hud.innerHTML,/vitality-damaged/);timers.beat();assert.match(g.nodes.hud.innerHTML,/vitality-damaged/);g.state.save();g.state.load();g.ui.route('explore');assert.doesNotMatch(g.nodes.hud.innerHTML,/vitality-damaged/);});
test('poison rescue reports only HP actually lost and healthy mushrooms show no damage',()=>{const g=game(new Map(),true);g.place('Food','mushrooms',27,0);g.state.data.level=100;g.ui.route('encounter');g.rng(.99);g.ui.dispatch('eat');assert.equal(g.state.data.hp.current,1);assert.equal(g.world.current().elementType,'Home');assert.match(g.nodes.toast.innerHTML,/−49 HP/);assert.match(g.nodes.hud.innerHTML,/−49 HP/);g.place('Food','mushrooms',3,3);g.ui.route('encounter');g.ui.dispatch('eat');assert.equal(g.state.data.hp.current,50);assert.match(g.nodes.toast.innerHTML,/HEALTH RESTORED/);assert.doesNotMatch(g.nodes.hud.innerHTML,/vitality-damaged/);});
test('winning blow stays visible before rewards; rapid taps cannot add another turn',()=>{const g=game(new Map(),true),timers=roundTimers(g);g.place('Danger','snake');g.rng(0);g.combat.start();g.state.data.battle.enemy.hp=1;g.ui.route('battle');g.ui.dispatch('attack:1');assert.equal(g.ui.screen,'battle');assert.match(g.nodes.stage.innerHTML,/combat-impact/);assert.match(g.nodes['combat-toasts'].innerHTML,/YOU HIT/);assert.doesNotMatch(g.nodes['combat-toasts'].innerHTML,/ENEMY DEFEATED/);assert.match(g.nodes.stage.innerHTML,/impact-badge/);g.ui.dispatch('attack:1');assert.equal(g.state.data.victories,1);timers.flush();assert.equal(g.ui.screen,'aftermath');assert.match(g.nodes['combat-toasts'].innerHTML,/ENEMY DEFEATED/);assert.match(g.nodes.stage.innerHTML,/YOUR REWARDS/);assert.match(g.nodes.stage.innerHTML,/Metal Ingot/);});
test('double misses stay blue/neutral with explicit labels and no screen shake',()=>{const g=game(new Map(),true),timers=roundTimers(g);g.place('Enemy','ogre',27,0);g.combat.start();g.rng(.9999);g.ui.route('battle');g.ui.dispatch('attack:1');assert.equal(g.state.data.battle.lastRound.dealt,0);assert.equal(g.state.data.battle.lastRound.received,0);assert.match(g.nodes['combat-toasts'].innerHTML,/YOU MISSED/);assert.doesNotMatch(g.nodes.stage.innerHTML,/ENEMY MISSED/);timers.beat();assert.match(g.nodes['combat-toasts'].innerHTML,/ENEMY MISSED/);assert.match(g.nodes['combat-toasts'].innerHTML,/round-event miss/);assert.ok(!g.nodes.stage.innerHTML.includes('combat-impact'));timers.flush();assert.match(g.nodes.stage.innerHTML,/MAKE YOUR MOVE/);});
test('defeat shows red damage and recovery, never reward collection',()=>{const g=game(new Map(),true),timers=roundTimers(g);g.place('Enemy','ogre',27,0);g.combat.start();g.state.data.battle.enemy.hp=1000;g.state.data.battle.enemy.basePower=1000;g.rng(0);g.ui.route('battle');g.ui.dispatch('attack:0');assert.doesNotMatch(g.nodes.stage.innerHTML,/round-event hurt/);timers.beat();assert.match(g.nodes['combat-toasts'].innerHTML,/round-event hurt/);assert.match(g.nodes['combat-toasts'].innerHTML,/YOU TOOK DAMAGE/);timers.flush();assert.match(g.nodes.stage.innerHTML,/WAKE AT HOME/);assert.match(g.nodes.stage.innerHTML,/NO LOOT THIS TIME/);assert.ok(!g.nodes.stage.innerHTML.includes('CLAIM REWARDS'));assert.ok(!g.nodes.stage.innerHTML.includes('result-stat'));g.state.load();g.ui.init();assert.match(g.nodes.stage.innerHTML,/>RECOVER</);assert.ok(!g.nodes.stage.innerHTML.includes('CLAIM REWARDS'));g.ui.route('aftermath');g.ui.dispatch('recover');assert.equal(g.ui.screen,'explore');assert.equal(g.state.data.hp.current,1);assert.equal(g.world.current().resolved,true);assert.match(g.nodes.stage.innerHTML,/CHOOSE YOUR PATH/);assert.match(g.nodes.toast.innerHTML,/SAFELY HOME/);assert.equal(g.state.data.inventory.length,0);});
test('claim toast identifies quantities, merges duplicate loot and never re-awards it',()=>{const g=game(new Map(),true);g.state.add('MetalIngot',5);g.state.add('Gem',1);g.state.data.outcome={win:true,rewards:[{type:'MetalIngot',qty:2},{type:'MetalIngot',qty:3},{type:'Gem',qty:1}],levels:0,enemy:'Ogre',art:'warrior-sword'};g.ui.route('aftermath');assert.equal((g.nodes.stage.innerHTML.match(/class="reward-item"/g)||[]).length,2);assert.match(g.nodes.stage.innerHTML,/>\+5</);g.ui.dispatch('claim');assert.match(g.nodes.toast.innerHTML,/LOOT SECURED/);assert.match(g.nodes.toast.innerHTML,/\+5 Metal Ingot · \+1 Gem/);assert.equal(g.nodes.toast.className,'toast-reward');g.ui.dispatch('claim');assert.equal(g.state.qty('MetalIngot'),5);assert.equal(g.state.qty('Gem'),1);});
test('leaving battle cancels the pending presentation timer without discarding its outcome',()=>{const g=game(new Map(),true),timers=roundTimers(g);g.place('Danger','snake');g.combat.start();g.state.data.battle.enemy.hp=1;g.rng(0);g.ui.route('battle');g.ui.dispatch('attack:1');g.ui.route('pack');timers.flush();assert.equal(g.ui.screen,'pack');assert.equal(g.state.data.outcome.win,true);g.ui.route('explore');assert.match(g.nodes.stage.innerHTML,/VIEW REWARDS/);});
test('magic has its own outcome color and consumes a crystal exactly once',()=>{const g=game(new Map(),true);roundTimers(g);g.place('Enemy','ogre',27,0);g.combat.start();g.state.data.battle.enemy.hp=1000;g.state.add('MagicCrystal');g.rng(0);g.ui.route('battle');g.ui.dispatch('attack:3');assert.match(g.nodes['combat-toasts'].innerHTML,/round-event magic-hit/);assert.match(g.nodes['combat-toasts'].innerHTML,/Realmfire/);assert.equal(g.state.qty('MagicCrystal'),0);g.ui.dispatch('attack:3');assert.equal(g.state.data.battle.round,2);});
if(process.env.ASSET_AUDIT){test('every rendered image, manifest entry and stylesheet reference exists',()=>{const g=game(new Map(),true);const refs=new Set();const collect=()=>{for(const html of [g.nodes.stage.innerHTML,g.nodes.hud.innerHTML])for(const m of html.matchAll(/(?:src|href)="(assets\/[^"#]+)"/g))refs.add(m[1]);};g.ui.init();for(const page of ['title','explore','pack','forge','map','hero','journal']){g.ui.route(page);collect();}for(const e of Object.values(g.content.entities))for(const outer of [false,true]){g.place(e.type,e.id,outer?27:3,3);g.ui.route('encounter');collect();}for(const type of Object.keys(g.content.weapons)){g.state.data.weapon=g.content.weapon(type);g.ui.route('hero');collect();}for(const m of fs.readFileSync(path.join(root,'css/game.css'),'utf8').matchAll(/url\(['"]?\.\.\/(assets\/[^)'";]+)['"]?\)/g))refs.add(m[1]);const manifest=JSON.parse(fs.readFileSync(path.join(root,'assets/manifest.json'),'utf8'));for(const entry of Object.values(manifest))for(const k of ['file','village','outer'])if(entry[k])refs.add('assets/'+entry[k]);for(const ref of refs)assert.ok(fs.existsSync(path.join(root,ref)),ref);console.log('Verified '+refs.size+' distinct referenced assets.');});}


test('defeated coordinates stay safe across repeated walks and reloads without farmable rewards',()=>{
  for(const [type,id,x] of [['Danger','bat',3],['Enemy','ogre',27],['Dragon','dragon',27]]){
    const g=game(new Map(),true);g.rng(0);const tile=g.place(type,id,x,3);
    if(type==='Dragon')tile.dragonHp=300;
    g.combat.start();g.state.data.battle.enemy.hp=1;g.combat.attack(0);g.combat.claim();
    const loot=JSON.stringify(g.state.data.inventory);
    for(let i=0;i<4;i++){
      assert.ok(g.world.move('E'));assert.ok(g.world.move('W'));g.state.load();
      assert.equal(g.world.current().elementType,'Nature');assert.equal(g.world.current().cleared,true);
      assert.equal(g.combat.start(),false);assert.equal(g.state.data.victories,1);
      assert.equal(JSON.stringify(g.state.data.inventory),loot);
    }
    g.ui.route('explore');assert.match(g.nodes.stage.innerHTML,/No threat remains here/);
    assert.doesNotMatch(g.nodes.stage.innerHTML,/ENTER BATTLE/);
  }
});

test('bribed threats stay cleared while fleeing leaves an undefeated threat behind',()=>{
  const g=game();g.place('Enemy','ogre',27,3);g.state.add('Gem');g.combat.start();g.combat.bribe();g.combat.claim();
  g.world.move('E');g.world.move('W');assert.equal(g.world.current().cleared,true);assert.equal(g.combat.start(),false);
  const h=game();h.place('Danger','bat');h.combat.start();h.combat.flee();h.world.move('E');h.world.move('W');
  assert.equal(h.world.current().elementType,'Danger');assert.ok(!h.world.current().cleared);assert.ok(h.combat.start());
});

test('legacy resolved clearings migrate safely without marking new resource clearings as victories',()=>{
  const g=game();g.place('Danger','skeleton');g.world.clear();delete g.world.current().cleared;
  g.state.save();g.state.load();assert.equal(g.world.current().cleared,true);
  g.world.move('E');g.world.move('W');assert.equal(g.world.current().elementType,'Nature');
  const h=game();h.place('Food','mushrooms');h.state.data.hp.current=25;h.actions.eat();h.state.load();
  assert.equal(h.world.current().cleared,false);
});

test('creatures use natural attacks and small creatures have no armor at any level',()=>{
  for(const id of ['bat','snake','spider','gargoyle','dragon'])for(const level of [1,20]){
    const g=game(new Map(),true);g.state.data.level=level;
    const type=g.content.entities[id].type,b=g.place(type,id,27,3);if(id==='dragon')b.dragonHp=500;
    g.combat.start();const e=g.state.data.battle.enemy;
    assert.equal(e.weapon,null);assert.ok(e.attackStyle);assert.ok(e.moves.every(m=>m.accuracy>0&&m.accuracy<=100));
    assert.ok(e.moves.every(m=>!['Stab','Backstab','Slash','Cleave','Crush','Earthshaker','Chop','Execution'].includes(m.name)));
    if(['bat','snake','spider'].includes(id)){assert.equal(e.resistance,0);assert.equal(e.defense,null);}
    else{assert.ok(e.resistance>0);assert.ok(['Scales','Stone hide'].includes(e.defense));}
    g.ui.route('battle');const enemyCard=g.nodes.stage.innerHTML.match(/class="fighter enemy"><div class="fighter-info">([\s\S]*?)<\/div><\/div>/)[1];
    assert.doesNotMatch(enemyCard,/% ARM|Knife|Sword|Hammer/);assert.match(enemyCard,/Fangs|Talons|Claws/);
  }
  for(const [id,weapon] of [['skeleton','Sword'],['ogre','Axe'],['troll','Hammer']]){
    const g=game();g.place(g.content.entities[id].type,id,27,3);g.combat.start();
    assert.equal(g.state.data.battle.enemy.weapon,weapon);assert.ok(g.state.data.battle.enemy.resistance>0);
  }
});

test('an existing creature battle sheds old equipment without losing health or progress',()=>{
  const g=game();g.place('Danger','bat');g.combat.start();const e=g.state.data.battle.enemy;
  Object.assign(e,{hp:12,weapon:'Knife',resistance:15,moves:g.content.weapon('Knife').moves.filter(m=>!m.magic)});
  delete e.attackStyle;delete e.defense;g.state.data.battle.round=4;g.state.save();g.state.load();
  const saved=g.state.data.battle;assert.equal(saved.round,4);assert.equal(saved.enemy.hp,12);
  assert.equal(saved.enemy.weapon,null);assert.equal(saved.enemy.resistance,0);
  assert.deepEqual(Array.from(saved.enemy.moves,m=>m.name),['Wing Bash','Bite','Diving Bite']);
});


test('passing any NPC silently clears old narration and returns to directions without journal noise',()=>{
  for(const id of ['villager','farmer','woodcutter','hunter','elder'])for(const x of [3,27]){
    const g=game(new Map(),true);g.place('NPC',id,x,3);g.state.log('An earlier event.');
    const count=g.state.data.journal.length;g.ui.dispatch('ignore');
    assert.equal(g.state.data.message,'');assert.equal(g.state.data.journal.length,count);
    assert.equal(g.world.current().resolved,true);assert.match(g.nodes.stage.innerHTML,/CHOOSE YOUR PATH/);
    assert.doesNotMatch(g.nodes.stage.innerHTML,/recent-message|An earlier event|Another fight/);
    g.state.load();g.ui.route('explore');assert.doesNotMatch(g.nodes.stage.innerHTML,/recent-message/);
  }
});

test('old generic walking-away banners disappear on load while journal history stays intact',()=>{
  for(const line of ['Not every shadow needs your steel.','You leave it to the forest.','Another day. Another fight.']){
    const g=game(new Map(),true);g.place('NPC','elder');g.world.current().resolved=true;
    g.state.log(line);g.state.save();g.state.load();g.ui.route('explore');
    assert.equal(g.state.data.message,'');assert.equal(g.state.data.journal.at(-1),line);
    assert.doesNotMatch(g.nodes.stage.innerHTML,/recent-message/);
  }
});

test('walking-away narration reflects threats, untouched items, used forges and partial digs',()=>{
  for(const [type,id,pattern] of [
    ['Danger','bat',/You avoid Angry Bat. The threat remains here/],
    ['Enemy','ogre',/You avoid Ironjaw Ogre. The threat remains here/],
    ['Dragon','dragon',/You avoid Verdant Dragon. The threat remains here/],
    ['Food','mushrooms',/mushrooms untouched/],['LockedItem','chest',/chest locked/],
    ['BuriedItems','dig',/disturbed earth untouched/],['Craft','forge',/step away from the forge/]
  ]){
    const g=game();const b=g.place(type,id,27,3);g.actions.ignore();
    assert.match(g.state.data.message,pattern);assert.equal(b.elementType,type);
    assert.doesNotMatch(g.state.data.message,/Another day|Another fight|leave it to the forest|poison/i);
  }
  const g=game();g.place('BuriedItems','dig');g.rng(0);g.actions.dig();g.actions.ignore();
  assert.match(g.state.data.message,/stop digging.*unfinished hole/);assert.equal(g.world.current().dug,1);
  g.place('Craft','forge');g.state.add('SteelIngot',6);g.actions.craft('weapon');g.actions.ignore();
  assert.match(g.state.data.message,/step away from the forge/);assert.equal(g.state.data.weapon.basePower,6);
});

test('weapon narration fits hammers and chest narration identifies the actual collected loot',()=>{
  const g=game(new Map(),true);g.state.data.weapon=g.content.weapon('Hammer');g.place('NPC','elder');
  g.actions.talk(true);assert.match(g.world.current().dialogue.narration,/beyond your reach/);
  g.state.add('SteelIngot',6);g.actions.craft('weapon');assert.match(g.state.data.message,/hammer is reinforced/);
  g.ui.route('forge');assert.match(g.nodes.stage.innerHTML,/REFORGE/);assert.doesNotMatch(g.nodes.stage.innerHTML,/RESHARPEN/);
  g.place('LockedItem','chest',27,3);g.state.add('Key');g.rng(0);g.actions.unlock();
  assert.equal(g.state.qty('Key'),0);assert.match(g.state.data.message,/unlock the chest.*Metal Ingot added to your pack/);
  assert.equal(g.state.qty('MetalIngot'),1);
});


test('battle notices stack outside the page, expire independently, and never replay on a rerender',()=>{
  const g=game(new Map(),true),timers=roundTimers(g);g.place('Enemy','ogre',27,0);g.rng(0);g.combat.start();g.ui.route('battle');
  const stack=g.nodes['combat-toasts'];assert.match(stack.innerHTML,/CHOOSE YOUR OPENING/);assert.doesNotMatch(g.nodes.stage.innerHTML,/CHOOSE YOUR OPENING|combat-log|round-feedback/);
  g.ui.dispatch('attack:0');assert.equal(stack.children.length,1);assert.match(stack.innerHTML,/YOU HIT/);assert.doesNotMatch(stack.innerHTML,/CHOOSE YOUR OPENING|YOU TOOK DAMAGE/);
  const first=stack.children[0];timers.beat();assert.equal(stack.children.length,2);assert.equal(stack.children[0],first);assert.match(stack.innerHTML,/YOU HIT[\s\S]*YOU TOOK DAMAGE/);
  timers.flush();g.ui.render(true);assert.equal(stack.children.length,2);assert.doesNotMatch(g.nodes.stage.innerHTML,/round-event|combat-log|round-feedback/);
  const expiring=[...timers.pending].filter(([,t])=>t.ms===5000);assert.equal(expiring.length,2);
  expiring[0][1].fn();assert.equal(stack.children.length,1);assert.doesNotMatch(stack.innerHTML,/YOU HIT/);
  expiring[1][1].fn();assert.equal(stack.children.length,0);g.ui.render(true);assert.equal(stack.children.length,0);
  g.state.load();g.ui.init();g.ui.route('battle');assert.equal(stack.children.length,0);
});

test('new rounds replace old notices and leaving battle cancels the pending enemy toast',()=>{
  const g=game(new Map(),true),timers=roundTimers(g);g.place('Enemy','ogre',27,0);g.rng(.9999);g.combat.start();g.ui.route('battle');
  g.ui.dispatch('attack:0');timers.flush();assert.equal(g.nodes['combat-toasts'].children.length,2);
  g.ui.dispatch('attack:0');assert.equal(g.nodes['combat-toasts'].children.length,1);assert.match(g.nodes['combat-toasts'].innerHTML,/ROUND 2/);
  g.ui.route('pack');timers.flush();assert.equal(g.nodes['combat-toasts'].children.length,0);
  assert.equal([...timers.pending.values()].filter(t=>t.ms===5000).length,0);
});


test('new-coordinate rates reserve quiet terrain, scarce NPCs and increased outer threats',()=>{
  for(const local of [true,false]){
    const g=game(),rates=g.content.encounterRates(local);
    assert.equal(rates.Nature,40);assert.equal(rates.NPC,local?10:5);
    assert.ok(Math.abs(Object.values(rates).reduce((a,b)=>a+b,0)-100)<1e-10);
    const threats=['Danger','Enemy','Dragon'];
    if(!local){assert.ok(Math.abs(threats.reduce((sum,type)=>sum+rates[type],0)-20)<1e-10);assert.equal(rates.Danger,rates.Enemy);assert.equal(rates.Danger,4*rates.Dragon);}
    const others=Object.entries(rates).filter(([type])=>type!=='Nature'&&type!=='NPC'&&(local||!threats.includes(type)));
    const totalWeight=others.reduce((sum,[type])=>sum+g.content.weights[type],0);
    for(const [type,rate] of others)assert.ok(Math.abs(rate-(local?50:35)*g.content.weights[type]/totalWeight)<1e-10,type);
    assert.equal(Object.hasOwn(rates,'Home'),false);
    for(const type of g.content.outerOnly)assert.equal(Object.hasOwn(rates,type),!local);
    let start=0,i=0;
    for(const [type,rate] of Object.entries(rates)){
      g.rng((start+rate/2)/100);assert.equal(g.world.getOrCreateBlock(local?3:27,3+i++).elementType,type);start+=rate;
    }
    g.rng(.399999);assert.equal(g.world.getOrCreateBlock(local?4:28,3).elementType,'Nature');
    g.rng(.4);assert.equal(g.world.getOrCreateBlock(local?4:28,4).elementType,'NPC');
    g.rng(local?.5:.45);assert.equal(g.world.getOrCreateBlock(local?4:28,5).elementType,'Food');
  }
});

test('new scenery, animals and grave can spawn, render in both realms and survive a save',()=>{
  const added={Nature:['forest-path','dense-woodland','leafy-clearing','grassy-rise'],Animal:['boar','hedgehog','otter','marten'],Thing:['grave']};
  const g=game(new Map(),true);g.ui.init();
  for(const [type,ids] of Object.entries(added))for(const id of ids)for(const local of [true,false]){
    const pool=Object.values(g.content.entities).filter(e=>e.type===type);
    g.rng((pool.findIndex(e=>e.id===id)+.5)/pool.length);
    assert.equal(g.world.spawn(type,local?6:29,6).subtype,id);
    g.place(type,id,local?6:29,6);g.ui.route('explore');
    assert.match(g.nodes.stage.innerHTML,new RegExp('assets/'+id+'-'+(local?'village':'outer')+'\\.png'));
    g.state.save();g.state.load();assert.equal(g.world.current().subtype,id);
    assert.equal(g.world.current().elementType,type);
  }
});
